### PR TITLE
Fixing homepage

### PR DESCRIPTION
**Pull request by just-Muzz**

### CODE REVIEW

**Comment by vivaan2006** [comment]
error on my side when running

**Comment by just-Muzz** [comment]
what error

**Comment by vivaan2006** [comment]
[plugin:vite:esbuild] Transform failed with 1 error:
/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/src/App.tsx:52:1: ERROR: The character ">" is not valid inside a JSX element
/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/src/App.tsx:58:0
The character ">" is not valid inside a JSX element
50 |            <Route path="about" element={<About />} />
51 |            <Route path="getinvolved" element={<GetInvolved />} />
52 |  />
   |   ^
53 |  
54 |          </Routes>
    at failureErrorWithLog (/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/Vivaan/Desktop/Silverline/Silverline-College-Counseling-Expansion/frontend/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23

**Comment by just-Muzz** [comment]
Seen

**Pull request closed without merging**
